spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/gaadix_notification_db
    username: KD2-GANESH-92393
    password: manager
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8087

# Notification Configuration (Mock)
notification:
  email:
    enabled: true
    from: noreply@gaadix.com
  sms:
    enabled: true
    provider: mock
  push:
    enabled: true
    provider: mock
